'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';

export default function Page() {
  const [collateral, setCollateral] = useState(1000000), [loan, setLoan] = useState(300000), [drop, setDrop] = useState(20), [warning, setWarning] = useState(70);
  const result = useMemo(() => { const value = Math.max(0, collateral) * (1 - Math.max(0, drop) / 100); const ltv = value > 0 ? Math.max(0, loan) / value * 100 : 0; return { value, ltv, room: value * Math.max(0, warning) / 100 - Math.max(0, loan) }; }, [collateral, loan, drop, warning]);
  const yen = new Intl.NumberFormat('ja-JP', { maximumFractionDigits: 0 }); const pct = new Intl.NumberFormat('ja-JP', { maximumFractionDigits: 1 });
  return <div className="calculator-page"><header className="calculator-intro"><p className="page-kicker">CRYPTO / LTV CALCULATOR</p><h1>担保余力を、<br /><em>LTVで見える化。</em></h1><p className="lede">暗号資産の担保評価額、借入額、価格下落率を入力し、下落後のLTVと警告水準までの余力を概算します。</p><div className="calculator-proof"><span>価格下落を反映</span><span>警告水準を変更</span><span>入力は端末内で計算</span></div></header><div className="calculator-shell"><div className="calculator-grid"><section className="calculator-inputs"><div className="calculator-panel-head"><div><span>INPUT</span><h2>担保・借入条件</h2></div></div><div className="field-grid"><label><span>担保評価額（円）</span><input type="number" min="0" step="10000" value={collateral} onChange={e => setCollateral(Number(e.target.value))} /></label><label><span>借入残高（円）</span><input type="number" min="0" step="10000" value={loan} onChange={e => setLoan(Number(e.target.value))} /></label><label><span>想定価格下落率（％）</span><input type="number" min="0" max="100" step="1" value={drop} onChange={e => setDrop(Number(e.target.value))} /></label><label><span>警告水準（LTV・％）</span><input type="number" min="1" max="100" step="1" value={warning} onChange={e => setWarning(Number(e.target.value))} /></label></div></section><section className="calculator-result"><div className="result-head"><span>ESTIMATE</span><h2>下落後のLTV</h2></div><div className="total-cost"><strong>{pct.format(result.ltv)}</strong><span>％</span></div><p>{result.ltv >= warning ? '警告水準以上の試算' : '警告水準未満の試算'}</p><p>下落後の担保評価額：約{yen.format(result.value)}円</p><p>LTV{warning}％までの余力：約{yen.format(Math.max(0, result.room))}円</p></section></div></div><div className="callout"><strong>サービスごとの判定を優先してください</strong><p>担保掛目、価格更新、警告・強制決済の水準はサービスごとに異なります。この計算機は単純化した概算であり、借入を推奨するものではありません。</p></div><nav className="calculator-proof" aria-label="関連ガイド"><Link href="/articles/crypto-collateral-loan-risk-checklist">暗号資産担保ローンの確認項目</Link><Link href="/crypto">暗号資産のスプレッド実測</Link></nav></div>;
}
