export const POSTS = [
  { slug: 'dmm-fx-funding-transfer', category: 'FX・DMM FX', title: 'DMM FXの入金方法と証拠金振替｜5,000円・出金・株券担保', desc: 'クイック入金・振込入金、最低額、反映時間、出金、DMM 株からの株券担保振替を整理する。' },
  { slug: 'dmm-fx-trade-history-csv', category: 'FX・DMM FX・税金', title: 'DMM FXの取引履歴をCSV保存する方法｜約定履歴・期間損益・年間報告書', desc: 'DMM FXの約定履歴をPC・スマホで確認し、CSV・期間損益・年間損益報告書を確定申告用に使い分ける。' },
  { slug: 'tossy-trading-hours-rollover', category: 'CFD・TOSSY', title: 'TOSSYの取引時間とロールオーバー｜休場・持越しを確認', desc: 'TOSSYのアセット別取引時間、日次・週次メンテナンス、ロールオーバー、価格調整額、注文取消しを整理する。' },
  { slug: 'tossy-deposit-withdrawal-transfer', category: 'CFD・TOSSY', title: 'TOSSYの入金・出金・振替方法｜5,000円・2,000円・3営業日を整理', desc: '銀行振込・クイック入金・他サービスからの振替入金、出金条件、反映時間、同名義ルールを整理する。' },
  { slug: 'fx-cfd-futures-margin-comparison', category: 'FX・CFD・先物比較', title: 'FX・CFD・先物の違い｜必要証拠金と1単位の損益を比較', desc: 'FX・CFD・日経225先物を、取引単位、証拠金、最小値動き、ロスカット・追証、期限の違いで比較する。' },
  { slug: 'dmm-kabu-shareholder-benefit', category: '国内株・DMM 株', title: 'DMM 株の株主優待はいつ？権利付き最終日と探し方を整理', desc: '株主優待の権利付き最終日・権利落ち日、アプリでの探し方、現物・信用・単元未満株の違いを整理する。' },
  { slug: 'jfx-allowed-spread-setting', category: 'FX・JFX', title: 'JFX許容スプレッド設定とは？急拡大時の注文を止める方法', desc: '許容スプレッドと許容スリップの違い、設定手順、注文不成立の条件、米ドル円のコスト例を整理する。' },
  { slug: 'matsui-fx-auto-trading-setting', category: 'FX自動売買・松井証券', title: 'MATSUI FX自動売買の設定方法｜レンジ・値幅・益出し幅を整理', desc: '注文レンジ、注文値幅、益出し幅、注文数量、運用停止ライン、最大100件の制限と必要資金の考え方を解説する。' },
  { slug: 'dmm-kabu-usd-shortage', category: '米国株・DMM 株', title: 'DMM 株の米ドル不足・立替金とは？強制為替取引と制限を解説', desc: '米ドル不足の原因、円貨・外貨決済、強制為替取引、取引・出金制限、解消方法を公式情報で整理する。' },
  { slug: 'dmm-kabu-us-dividend-tax', category: '米国株・DMM 株', title: 'DMM 株の米国株配当金と税金｜入金日・NISA・外国税額控除', desc: '米国10％と国内20.315％の課税、NISAの国内非課税、外国税額控除、ドル入金、入金反映日を整理する。' },
  { slug: 'dmm-kabu-us-stock-order-hours', category: '米国株・DMM 株', title: 'DMM 株の米国株取引時間・注文方法｜逆指値は使える？', desc: '夏時間・冬時間、注文受付、1株単位、成行・指値・IFDONE、逆指値非対応、最長30日の期限、円貨・外貨決済を整理する。' },
  { slug: 'dmm-kabu-order-types-expiration', category: '国内株・DMM 株', title: 'DMM 株の注文方法｜成行・指値・逆指値・OCOと失効条件', desc: '成行、指値、寄付、引け、不成、逆指値、OCO、IOC、注文期限、期限前に失効する条件、NISAの制限を整理する。' },
  { slug: 'dmm-kabu-fractional-shares-buyback', category: '国内株・DMM 株', title: 'DMM 株の単元未満株は売却できる？買取請求・手数料・NISAを整理', desc: '通常売却との違い、買取請求の操作、550円の取次手数料、価格決定、受付停止期間、NISAでの取扱いを整理する。' },
  { slug: 'dmm-kabu-tob-application', category: '国内株・DMM 株', title: 'DMM 株のTOB申込方法｜移管・手数料・NISA株の注意点', desc: '対象銘柄、PCでの申込、他社からの移管、無料範囲、申込取消、NISAから課税口座への振替を整理する。' },
  { slug: 'dmm-kabu-us-margin-vip-courses', category: '米国株・DMM 株', title: 'DMM 株の米国株信用メンバー・プレミアム条件｜金利差を計算', desc: 'ゲスト・メンバー・プレミアムを、入庫額、米ドル残高、平均建玉、手数料、買方金利、適用期間で比較する。' },
  { slug: 'dmm-kabu-us-margin-call', category: '米国株・DMM 株', title: 'DMM 株の米国株信用の追証｜30％・2,500ドルと解消期限', desc: '追証予定と確定の時刻、最低預託率30％、最低保証金2,500ドル、翌々国内営業日15時30分の期限、返済による解消を整理する。' },
  { slug: 'dmm-kabu-us-margin-cost', category: '米国株・DMM 株', title: 'DMM 株の米国株信用取引コスト｜手数料・金利・保証金を計算', desc: 'ゲスト・メンバー・プレミアムの取引手数料と買方金利、買建のみ、保証金率50％、追証30％を整理する。' },
  { slug: 'dmm-kabu-margin-account-opening', category: '国内株・DMM 株', title: 'DMM 株の信用取引口座開設｜申込方法・審査・必要資金を確認', desc: '総合口座と同時・追加で申し込む方法、審査期間、必要な経験・知識・資力、最低保証金30万円、NISAとの違いを整理する。' },
  { slug: 'dmm-kabu-margin-call-maintenance-rate', category: '国内株・DMM 株', title: 'DMM 株の追証はいくらから？保証金率30％・維持率20％を計算', desc: '最低保証金30万円、委託保証金率30％、最低預託率20％、追証の判定、期限、入金・返済による解消を整理する。' },
  { slug: 'dmm-kabu-margin-trading-cost', category: '国内株・DMM 株', title: 'DMM 株の信用取引手数料は無料？金利・貸株料・逆日歩を計算', desc: '0円の売買手数料と、買方金利、貸株料、逆日歩、事務管理費、名義書換料、デイトレ強制決済を整理する。' },
  { slug: 'dmm-kabu-ipo-application', category: '国内株・DMM 株', title: 'DMM 株のIPO申込方法｜前受金不要・完全平等抽選と当選後の手順', desc: '抽選時の資金、完全平等抽選、申込上限、当選・補欠当選後の購入意思表示、NISA口座区分を整理する。' },
  { slug: 'dmm-kabu-dividend-receiving-tax', category: '証券・DMM 株', title: 'DMM 株の配当金はいつ・どこに入る？受取方法と税金を整理', desc: '3つの配当金受取方式、入金時期、税率、特定口座の損益通算、NISAで非課税にする条件を整理する。' },
  { slug: 'dmm-kabu-specific-account-tax', category: '証券・DMM 株', title: 'DMM 株の特定口座｜源泉徴収あり・なし・一般口座と確定申告', desc: '3つの口座区分、年間取引報告書、確定申告、区分を変更できる条件、NISAとの違いを整理する。' },
  { slug: 'dmm-kabu-stock-transfer', category: '証券・DMM 株', title: 'DMM 株の株式移管｜入庫・出庫手数料と国内株・米国株の期間', desc: '他社との株式移管を、手数料、必要書類、預り区分、国内株・米国株の期間、NISA移管不可で整理する。' },
  { slug: 'dmmfx-stock-collateral-service', category: '株式・FX・DMM', title: 'DMMFX株券担保サービスとは？評価率70％・対象株・強制売却リスク', desc: 'DMM 株の保有株をDMM FXの証拠金へ使う仕組み、70％評価、対象外、振替時間、強制売却リスクを整理する。' },
  { slug: 'dmm-kabu-points-cash-exchange', category: '証券・DMM 株', title: 'DMM 株ポイントは何円？1％還元・現金交換・有効期限を計算', desc: '税抜取引手数料1％の計算、1pt＝1円の現金交換、付与日、有効期限、ポイントが付かない条件を整理する。' },
  { slug: 'dmm-kabu-tools-comparison', category: '証券・DMM 株', title: 'DMM 株のアプリ・取引ツール比較｜かんたん・ノーマル・STANDARD・PRO+', desc: 'スマホ2モードとPC2ツールを、注文、チャート、NISA、つみたてかぶ、利用環境で比較する。' },
  { slug: 'dmm-kabu-withdrawal-rules', category: '証券・DMM 株', title: 'DMM 株の出金はいつ？最低2,000円・手数料・売却代金の反映', desc: '最低出金額、手数料、予約時刻、国内株・米国株の売却代金、予約取消しの原因を整理する。' },
  { slug: 'dmm-kabu-deposit-methods', category: '証券・DMM 株', title: 'DMM 株の入金方法｜クイック入金5,000円・振込・反映時間', desc: 'クイック入金と振込入金を、最低金額、手数料、反映時間、同一名義、未反映時の確認手順で比較する。' },
  { slug: 'dmm-kabu-tsumitate-kabu-nisa', category: 'NISA・DMM 株', title: 'DMM 株のつみたてかぶは1,000円から｜NISA・手数料・買付日', desc: '1,000円からの株式積立、NISA対応、設定頻度、買付価格、共同買付、資金不足時の扱いを整理する。' },
  { slug: 'dmm-kabu-nisa-fees-products', category: 'NISA・DMM 株', title: 'DMM 株のNISAは手数料無料？国内株・米国株・為替コストを整理', desc: 'NISAで無料になる取引手数料と、米国株の為替コスト、外国配当税、国内株の配当受取方法を整理する。' },
  { slug: 'dmm-kabu-nisa-account-opening', category: 'NISA・DMM 株', title: 'DMM 株のNISA口座開設方法｜同時申込・追加申込・金融機関変更', desc: '新規アカウントとの同時申込、既存利用者の追加申込、他社からの金融機関変更に必要な書類を整理する。' },
  { slug: 'dmm-kabu-account-opening-documents', category: '証券・DMM 株', title: 'DMM 株の口座開設に必要なもの｜本人確認・マイナンバー・開始まで', desc: '本人確認とマイナンバー確認の組合せ、スマホと郵送の違い、審査から取引開始までを整理する。' },
  { slug: 'fx-etax-input-guide', category: 'FX・税金', title: 'FXの確定申告をe-Taxで入力する順番｜先物取引・経費・繰越損失', desc: '年間報告書の準備から、作成コーナーの「先物取引」、必要経費、繰越損失、e-Tax送信までを順番に整理する。' },
  { slug: 'fx-loss-carryforward-filing', category: 'FX・税金', title: 'FX損失を3年繰り越す確定申告｜取引しない年も必要？', desc: '損失発生年、利益が出た年、取引しない年に必要な連続申告と、計算明細書・繰越損失用付表を整理する。' },
  { slug: 'domestic-vs-overseas-fx-tax', category: 'FX・税金', title: '国内FXと海外FXの税金の違い｜20.315％・総合課税・損失繰越', desc: '申告分離課税と総合課税、損益通算、3年繰越を比較し、金融庁登録と取引の法的区分を確認する。' },
  { slug: 'fx-tax-rate-calculation', category: 'FX・税金', title: '国内FXの税率は20.315％？所得税・住民税の計算方法', desc: '所得税15％、復興特別所得税、地方稅5％の内訳と、必要経費・損益通算後の税額を計算する。' },
  { slug: 'fx-profit-under-200k-tax-return', category: 'FX・税金', title: 'FX利益20万円以下なら確定申告は不要？住民税・還付申告の注意', desc: '会社員の所得税申告が不要になる条件と、住民税、還付申告、損失繰越を別々に確認する。' },
  { slug: 'fx-tax-deductible-expenses', category: 'FX・税金', title: 'FXの必要経費にできるものは？PC・通信費・VPS・書籍を整理', desc: 'PC、通信費、VPS、書籍、セミナー、情報サービスと、家事按分、減価償却、領収書の保存を整理する。' },
  { slug: 'fx-annual-transaction-report-tax-return', category: 'FX・税金', title: 'FXの年間取引報告書はどこを見る？複数口座の確定申告準備', desc: '決済損益、スワップ、手数料、集計期間の確認と、複数口座の集計、確定申告書等作成コーナーへの入力準備を整理する。' },
  { slug: 'crypto-tax-reform-start-date', category: '暗号資産・税制', title: '暗号資産の分離課税はいつから？税制改正の対象・20％・損失繰越', desc: '改正金商法の施行日から決まる開始時期、特定暗号資産、20％分離課税、3年繰越、デリバティブの扱いを整理する。' },
  { slug: 'fx-profit-loss-offset-tax', category: 'FX・税金', title: 'FXの損益通算は何とできる？CFD・先物・株・暗号資産を整理', desc: '国内FXと一定のCFD・先物、株式、暗号資産の損益通算可否と、3年間の損失繰越に必要な申告を整理する。' },
  { slug: 'fx-multiple-accounts-cost-risk', category: 'FX・口座管理', title: 'FX口座を複数持つメリット・デメリット｜資金と損益の管理方法', desc: '2社以上を使い分ける利点と、証拠金の分散、ロスカット、損益集計、管理負担などの注意点を整理する。' },
  { slug: 'fx-company-selection-cost-checklist', category: 'FX・口座比較', title: 'FX会社はスプレッドだけで選ばない｜口座比較7項目', desc: 'スプレッドの適用時間、数量、約定、スワップ、最低取引単位、ロスカット、入出金を確認する順番を整理する。' },
  { slug: 'fx-spread-difference-annual-cost', category: 'FX・基礎計算', title: 'FXのスプレッド差0.1銭は年間いくら？数量・回数別に比較', desc: '米ドル円のスプレッド差0.1銭を、1,000通貨・1万通貨・10万通貨と1日1回・5回の年間コスト差へ換算する。' },
  { slug: 'fx-spread-monthly-cost', category: 'FX・基礎計算', title: 'FXのスプレッドは月いくら？取引回数別にコストを計算', desc: '米ドル円0.2銭を例に、1,000通貨・1万通貨・10万通貨の1回と月間20日・1日5回の負担を円で計算する。' },
  { slug: 'fx-master-guide-study-order', category: 'FX・学習', title: 'FX初心者は何から勉強する？9章を5段階で読む順番', desc: 'FXの仕組み、口座条件、注文、資金管理、経済、チャート、通貨ペアを、取引を急がず数字で確認する学習順に並べる。' },
  { slug: 'fpo-fx-master-guide-before-download', category: 'FX・学習', title: 'FPO FX投資マスターガイドは無料？登録前に確認する7項目', desc: '全128ページの無料電子書籍について、収録範囲、受取方法、メール登録、追加案内、投資リスク、使い方を公式情報から確認する。' },
  { slug: 'fpo-fx-practice-checklist', category: 'FX教材・FPO', title: 'FPOのFX教材を読んだ後に確認する実践チェックリスト', desc: '教材で学んだ後に、スプレッド、必要証拠金、損切り、取引記録、税務を実践前に確認する。' },
  { slug: 'dmm-cfd-index-vs-commodity', category: 'CFD・DMM CFD', title: 'DMM CFDのIndexとCommodityの違い｜22銘柄・証拠金を比較', desc: '株価指数8銘柄と商品14銘柄を、レバレッジ、取引単位、円換算、調整額、入金方法から比較する。' },
  { slug: 'dmm-cfd-account-opening-documents', category: '商品CFD・DMM CFD', title: 'DMM CFDの口座開設に必要なもの｜本人確認・審査・開始まで', desc: '本人確認とマイナンバーの組合せ、スマホと郵送の違い、審査から取引開始までを整理する。' },
  { slug: 'dmm-cfd-annual-profit-report', category: 'CFD・DMM CFD・税金', title: 'DMM CFDの年間損益報告書はいつ？出力方法と確定申告準備', desc: '年間損益・期間損益・約定履歴の違い、PC・スマホでの出力方法、他社取引との合算準備を整理する。' },
  { slug: 'dmm-cfd-deposit-minimum-quick', category: '商品CFD・DMM CFD', title: 'DMM CFDの最低入金額はいくら？クイック入金と振込を比較', desc: '初回最低入金額、クイック入金5,000円以上、振込手数料、出金条件と必要証拠金を分けて確認する。' },
  { slug: 'dmm-cfd-tick-value-profit-loss', category: '商品CFD・DMM CFD', title: 'DMM CFDは1ティックいくら？商品14銘柄の損益早見表', desc: '商品14銘柄の1Lot取引単位と呼値から、最小値幅の米ドル・円損益、総コスト回収に必要なティック数を計算する。' },
  { slug: 'commodity-cfd-one-dollar-profit-loss', category: '商品CFD・基礎計算', title: '商品CFDは1ドル動くといくら？金・銀・原油・天然ガスの損益', desc: '1Lotの取引単位と米ドル円から、1ドル・0.1ドルの値動き損益、証拠金5％目安、コスト回収値幅を計算する。' },
  { slug: 'fxtf-vs-dmm-cfd-commodity', category: '商品CFD・比較', title: 'FXTF MT5とDMM CFDの商品CFDを比較｜金・銀・原油・天然ガス', desc: '共通4商品の1Lot、証拠金、スプレッド、新規手数料、スワップ・調整額と、取扱銘柄数の違いを整理する。' },
  { slug: 'fxtf-vs-dmm-cfd-gold', category: '商品CFD・比較', title: 'FXTF MT5とDMM CFDの金CFDを比較｜1Lot・証拠金・総コスト', desc: '同じ1トロイオンス・証拠金率5％の金CFDを、スプレッド、新規手数料、スワップ・金利調整額から比較する。' },
  { slug: 'fxtf-mt5-btc-jpy-vs-usd', category: '暗号資産CFD・FXTF', title: 'FXTF MT5のBTC/JPYとBTC/USDを比較｜証拠金の円換算が違う', desc: '0.01Lot、必要証拠金の参照レート、スプレッドの円換算、建玉連動手数料の違いを整理する。' },
  { slug: 'fxtf-mt5-silver-cfd-margin', category: '商品CFD・FXTF', title: 'FXTF MT5の銀CFDは1Lotいくら？必要証拠金・手数料・スワップ', desc: '銀1Lot＝10トロイオンスの想定元本、必要証拠金、建玉連動手数料、スプレッド、スワップを計算する。' },
  { slug: 'fxtf-mt5-oil-natural-gas-margin', category: '商品CFD・FXTF', title: 'FXTF MT5の原油・天然ガスCFDを比較｜1Lot・証拠金・手数料', desc: '原油10バレルと天然ガス100mmBtuを、必要証拠金、建玉連動手数料、スプレッド、スワップから比較する。' },
  { slug: 'fxtf-mt5-gold-cfd-margin', category: '商品CFD・FXTF', title: 'FXTF MT5の金CFDは1Lotいくら？必要証拠金・手数料・スワップ', desc: '金1Lotの想定元本、必要証拠金、建玉連動手数料、スプレッド、スワップを公式例から計算する。' },
  { slug: 'fxtf-mt5-btc-cfd-cost', category: '暗号資産CFD・FXTF', title: 'FXTF MT5のビットコインCFDは0.01Lotでいくら？証拠金・手数料', desc: 'BTC/JPY 0.01Lotの想定元本、必要証拠金、建玉連動手数料、スプレッド、保有費を分けて計算する。' },
  { slug: 'fxtf-mt5-commodity-vs-crypto-cfd', category: 'CFD・FXTF', title: 'FXTF MT5の商品CFDと暗号資産CFDを比較｜証拠金・1Lot・手数料', desc: '商品20倍と暗号資産2倍の個人レバレッジ、1Lot、必要証拠金、建玉連動手数料を比較する。' },
  { slug: 'fxtf-mt4-ea-vps-start', category: 'FX自動売買・FXTF', title: 'FXTF MT4でEA自動売買を始める手順｜VPS・コスト・停止対策', desc: 'PC版MT4、0.01Lot、バックテスト、建玉連動手数料、VPS、停止監視までを運用順に整理する。' },
  { slug: 'jfx-vs-fxtf', category: 'FX・比較', title: 'JFXとFXTFを比較｜スキャルピング・MT4・手数料の違い', desc: 'JFXのスキャルピング環境とFXTFのGX・MT4を、取引単位、発注方法、EA、TradingView、建玉連動手数料から比較する。' },
  { slug: 'systre-select-365-vs-matsui-auto-trading', category: 'FX自動売買・比較', title: 'シストレセレクト365とMATSUI FX自動売買を比較', desc: '選択型とリピート型、1万通貨と1通貨、利用料、対象通貨、必要資金の考え方から2つの自動売買を比較する。' },
  { slug: 'systre-select-365-start-operation-flow', category: 'FX自動売買', title: 'シストレセレクト365の基本操作｜ランキングから稼働まで', desc: 'ランキング、成績期間、最大ドローダウン、数量、リスクメーターを確認し、ストラテジーを稼働するまでの順序を整理する。' },
  { slug: 'systre-select-365-account-opening-flow', category: 'FX自動売買', title: 'シストレセレクト365の始め方｜口座開設から稼働まで', desc: 'くりっく365口座の有無で異なる申込経路、本人確認、カード登録、入金、ストラテジー稼働までを整理する。' },
  { slug: 'fxtf-trading-hours-swap-cutoff', category: 'FX・FXTF', title: 'FXTFの取引時間とメンテナンス｜スワップ判定は何時？', desc: 'GX・MT4の夏冬の取引停止時間、NY17時のスワップ判定、EA利用時の週末確認を整理する。' },
  { slug: 'fxtf-losscut-50-100', category: 'FX・FXTF', title: 'FXTFのロスカットは50％・100％｜GXとMT4の違い', desc: '通常時50％と日次判定100％を区別し、GXとMT4の判定時刻・境界条件の違いを整理する。' },
  { slug: 'fxtf-position-fee-calculation', category: 'FX・FXTF', title: 'FXTFの建玉連動手数料とは？保有中の数量を含めて計算', desc: '新規注文だけでなく同一銘柄・同一売買方向の保有数量を加える手数料ランクの計算方法を整理する。' },
  { slug: 'fxtf-account-opening-flow', category: 'FX・FXTF', title: 'FXTFの口座開設手順｜必要書類・提出先・取引開始まで', desc: 'スマホ本人確認と通常開設を分け、確認書類の提出方法、公式メール・郵送先、審査後の流れを整理する。' },
  { slug: 'tossy-margin-call-losscut', category: 'CFD・TOSSY', title: 'TOSSYの追証・ロスカット｜6資産へ及ぶマージンカット', desc: 'ロスカットと追加証拠金を区別し、未解消時に他のアセット区分まで強制決済される仕組みを整理する。' },
  { slug: 'tossy-fees-total-cost', category: 'CFD・TOSSY', title: 'TOSSYの手数料は無料？スプレッド・調整額まで計算', desc: '口座管理費・取引手数料0円だけで判断せず、スプレッド、金利・権利・価格調整、スリッページを整理する。' },
  { slug: 'tossy-margin-by-asset', category: 'CFD・TOSSY', title: 'TOSSYの必要証拠金｜6資産を100万円取引で比較', desc: 'FX、株式、株価指数、バラエティ、商品、暗号資産CFDの証拠金率を同じ取引金額で比較する。' },
  { slug: 'tossy-account-opening-flow', category: 'CFD・TOSSY', title: 'TOSSYの口座開設手順｜必要書類と取引開始前の確認', desc: '申込、本人確認、審査、ログイン情報取得、入金、商品別書面確認までを順番に整理する。' },
  { slug: 'fx-vps-auto-start-update', category: 'FX自動売買・VPS', title: 'FX VPS再起動後にEAを止めない｜自動起動と更新手順', desc: 'Windows更新やメンテナンス後にMT4・MT5・EAが停止したままにならないよう、自動起動、更新時間、ログ確認を整理する。' },
  { slug: 'fx-vps-vs-home-pc', category: 'FX自動売買・VPS', title: 'FX自動売買はVPSと自宅PCどちら？費用と停止リスク', desc: 'VPSの本体・RDS料金と、自宅PCの電気代・停電・再起動・遠隔復旧を同じ比較軸で整理する。' },
  { slug: 'fx-vps-rds-license', category: 'FX自動売買・VPS', title: 'FX VPSのRDSライセンスとは？月1,320円を計算', desc: 'Windows ServerでMT4・MT5を使う場合のRDSライセンスを、必要になる接続、人数、月額・年額から整理する。' },
  { slug: 'ablenet-win1-vs-win2', category: 'FX自動売買・VPS', title: 'ABLENET Win1とWin2の違い｜MT4・MT5何個まで？', desc: 'CPU、メモリ、MT4・MT5稼働目安、契約時・更新後料金、RDS込み年額からWin1とWin2を比較する。' },
  { slug: 'fx-vps-total-cost', category: 'FX自動売買・VPS', title: 'FX自動売買VPSの費用はいくら？RDS込み総コスト', desc: 'VPS本体料金だけでなく、WindowsのRDSライセンス、契約更新後の料金、取引回数あたりのインフラ費まで計算する。' },
  { slug: 'tossy-cfd-not-spot', category: 'CFD・TOSSY', title: 'TOSSYの株式・暗号資産は現物？6資産とCFDの違い', desc: 'TOSSYで扱う株式、為替、暗号資産、株価指数、商品資源を、現物保有ではなく差金決済取引として整理する。' },
  { slug: 'jfx-before-account-opening-checklist', category: 'FX・JFX', title: 'JFX口座開設前の確認7項目｜スキャルピング・Lot・必要資金', desc: '取引スタイル、Lot例外、スプレッド、ツール、実効レバレッジ、入出金、本人確認を一つの判断導線にまとめる。' },
  { slug: 'jfx-trade-history-csv-tax-report', category: 'FX・JFX・税金', title: 'JFXの取引履歴をCSV保存する方法｜確定申告用報告書との違い', desc: '約定・注文・入出金履歴の検索とCSV保存、個人口座の損益計算書との照合方法を整理する。' },
  { slug: 'jfx-required-margin-leverage', category: 'FX・JFX', title: 'JFXの必要証拠金はいくら？最大・実効レバレッジ', desc: '米ドル円1,000通貨の公式例から、想定元本、必要証拠金、最大レバレッジ、実効レバレッジを計算する。' },
  { slug: 'jfx-deposit-methods-comparison', category: 'FX・JFX', title: 'JFXの入金方法を比較｜クイック入金と銀行振込', desc: '最低1万円・約380行のクイック入金と、1万円未満にも使える銀行振込を手数料・反映時間で比較する。' },
  { slug: 'matsui-withdrawal-unavailable', category: '証券・松井証券', title: '松井証券で出金できない原因｜出金可能額・受渡日を確認', desc: '売却代金の受渡、商品口座からの振替、受付時間、当日入金、取引状況、登録銀行を順に切り分ける。' },
  { slug: 'matsui-withdrawal-methods-comparison', category: '証券・松井証券', title: '松井証券の出金方法を比較｜翌営業日・即時・MATSUI Bank', desc: '3種類の出金を、着金時期、手数料、金額上限、取消可否、ゆうちょ銀行の制限で比較する。' },
  { slug: 'matsui-deposit-methods-comparison', category: '証券・松井証券', title: '松井証券の入金方法を比較｜手数料・反映時間', desc: 'スイープ、MATSUI Bank、ネットリンク、らくらく振替、定期入金、銀行振込を比較する。' },
  { slug: 'matsui-ekyc-required-documents', category: '証券・松井証券', title: '松井証券の口座開設に必要な書類｜eKYC・マイナンバー', desc: '最短即日のeKYC、オンラインアップロード、郵送の違いと書類不備の防止点を整理する。' },
  { slug: 'matsui-simultaneous-account-opening', category: '証券・松井証券', title: '松井証券で同時開設できる口座｜NISA・FX・信用・先物', desc: '総合口座と同時に開設・申込みできる口座、追加口座、商品別審査の違いを整理する。' },
  { slug: 'jfx-demo-account-guide', category: 'FX・JFX', title: 'JFXデモ口座でできること｜利用期間・仮想資金・本番との違い', desc: '約3カ月の利用期間、仮想資金、デモレート、土日利用、ロスカット、本番移行の手順を整理する。' },
  { slug: 'jfx-mt5-tradingview-matrix-trader', category: 'FX・JFX', title: 'JFXのMT5・TradingView・MATRIX TRADERの違い', desc: '発注、口座情報、レート受信、チャート分析の役割から3つのツールを比較する。' },
  { slug: 'jfx-deposit-not-reflected', category: 'FX・JFX', title: 'JFXの入金が反映されない原因｜クイック入金・銀行振込', desc: '銀行引落し、終了操作、通信、口座番号、振込名義、メンテナンスを順番に切り分ける。' },
  { slug: 'jfx-trading-hours-maintenance', category: 'FX・JFX', title: 'JFXの取引時間｜夏時間・冬時間・メンテナンスと土日の注文', desc: '月曜開始・土曜終了、日締めによる通信切断、週末の予約注文、時間指定注文の違いを整理する。' },
  { slug: 'jfx-beginner-vs-matrix-trader', category: 'FX・JFX', title: 'JFXビギナーFXとMATRIX TRADERの違い｜100通貨・1,000通貨', desc: '最低取引単位、通貨ペア、分析ツール、キャンペーンからミニ口座と本口座を比較する。' },
  { slug: 'jfx-account-opening-flow', category: 'FX・JFX', title: 'JFXの口座開設に必要なもの｜本人確認・初回入金', desc: 'スマホ本人確認、必要書類、審査、ID受取、初回入金1万円から取引開始までを整理する。' },
  { slug: 'jfx-quick-order-settings', category: 'FX・JFX', title: 'JFXクイック注文の設定｜全決済・両建て・決済pip差', desc: '確認画面、Lot数、両建て、許容設定、全決済方式、決済pip差の誤操作防止ポイントを整理する。' },
  { slug: 'jfx-order-slippage-rules', category: 'FX・JFX', title: 'JFXの注文方法とスリッページ｜成行・ストリーミング・逆指値', desc: '約定優先、許容スリップ、注文不成立、許容スプレッドの違いを基本注文ごとに整理する。' },
  { slug: 'jfx-vs-dmm-fx', category: 'FX・比較', title: 'JFXとDMM FXを比較｜取引単位・時間帯・ロスカット', desc: '1,000通貨対応、通常・ミニ銘柄、米ドル円スプレッドの適用時間、ロスカット基準の違いを整理する。' },
  { slug: 'jfx-vs-matsui-fx', category: 'FX・比較', title: 'JFXと松井証券FXを比較｜少額練習か短期売買か', desc: '最低取引単位、米ドル円スプレッド、レバレッジ、自動売買、スキャルピングの違いから用途別に比較する。' },
  { slug: 'jfx-withdrawal-time-rules', category: 'FX・JFX', title: 'JFXの出金はいつ反映？時間・金額・取消条件', desc: 'リアルタイム出金と通常出金の金額、即時着金の時間、時間外処理、手数料、依頼後の取消可否を比較する。' },
  { slug: 'jfx-hedging-margin-cost', category: 'FX・JFX', title: 'JFXの両建ては証拠金が片側分？コストと危険性', desc: '同数量は片側分、多い方で計算される証拠金と、スプレッド・スワップ差・設定・ロスカットの注意点を整理する。' },
  { slug: 'jfx-swap-transfer-tax', category: 'FX・JFX', title: 'JFXのスワップ振替とは？出金と税金の注意点', desc: '決済せず1円単位でスワップを確定する仕組みと、未実現・確定申告・休日や年末の取引日の違いを整理する。' },
  { slug: 'jfx-fees-total-cost', category: 'FX・JFX', title: 'JFXの手数料は本当に無料？実質コストを整理', desc: '取引・入出金・ロスカット手数料と、スプレッド・スワップ・スリッページなど残るコストを分けて確認する。' },
  { slug: 'jfx-lot-trade-unit', category: 'FX・JFX', title: 'JFXの1Lotはいくら？1,000通貨・1万通貨の例外', desc: '基本1Lot＝1,000通貨と6通貨ペアの1万通貨例外を分け、値動き損益・pips・スプレッド相当額を計算する。' },
  { slug: 'jfx-losscut-margin-shortage', category: 'FX・JFX', title: 'JFXのロスカット基準は？有効証拠金・必要証拠金と不足金', desc: '数秒間隔の判定、全ポジション決済、レート停止時の扱い、不足金の差入れ期限を公式書面から整理する。' },
  { slug: 'jfx-scalping-spread-cost', category: 'FX・JFX', title: 'JFXはスキャルピング向き？米ドル円の時間帯別スプレッドを計算', desc: '米ドル/円0.2銭と早朝5.9銭を、1,000通貨・1万通貨・取引回数ごとの円コストへ換算する。' },
  { slug: 'nikkei225-micro-profit-loss', category: '先物・日経225', title: '日経225マイクロは1円・1ティックでいくら？損益早見表', desc: '日経225マイクロ先物の10倍という取引単位と5円の呼値から、1枚の値動き損益と手数料分岐を計算する。' },
  { slug: 'fx-swap-spread-break-even-days', category: 'FX・スワップ', title: 'FXスワップでスプレッドを回収するまで何日？損益分岐を計算', desc: 'スプレッド相当額を1日分の受取スワップで割り、初期コスト回収日数と為替変動の影響を計算する。' },
  { slug: 'trading-cost-break-even-return', category: '資金管理・計算', title: '取引コストの損益分岐点は何％？手数料負けしない値幅を計算', desc: '往復手数料、スプレッド、保有コストを取引金額に対する比率へ直し、利益に必要な値幅を計算する。' },
  { slug: 'us-stock-yen-sensitivity', category: '米国株・為替', title: '米国株はドル円が1円動くといくら変わる？為替感応度早見表', desc: '保有する米国株のドル評価額から、ドル円が1円・5円・10円動いた場合の円換算額の変化を計算する。' },
  { slug: 'us-stock-loss-yen-depreciation', category: '米国株・為替', title: '米国株が下がっても円換算で利益？円安と損益分岐ドル円', desc: '株価下落と円安を同時に計算し、円換算で利益が残るドル円の境界とコストの影響を整理する。' },
  { slug: 'us-stock-profit-yen-appreciation', category: '米国株・為替', title: '米国株が上がったのに円換算で損？円高と損益分岐ドル円', desc: '株価上昇率と円高を同時に計算し、売買コストを含む円換算損益の見方を整理する。' },
  { slug: 'risk-reward-break-even-win-rate', category: '資金管理・計算', title: 'リスクリワード1対2の損益分岐勝率は？コスト込みで計算', desc: '損失と利益の比率から、取引コストを反映した損益分岐勝率と期待値を計算する。' },
  { slug: 'fx-one-pip-value', category: 'FX・基礎計算', title: 'FXの1pipsはいくら？1,000通貨・1万通貨の損益早見表', desc: 'クロス円とドルストレートの1pipsを、取引数量と円換算レートから具体的に計算する。' },
  { slug: 'fx-position-size-calculation', category: 'FX・リスク管理', title: 'FXの適正ロット・取引数量の決め方｜許容損失から逆算', desc: '口座資金、許容損失率、損切り幅、1pipsの損益から、取引数量を通貨単位で逆算する。' },
  { slug: 'matsui-futures-normal-vs-day', category: '先物・松井証券', title: '松井証券の先物手数料｜通常と一日先物を往復比較', desc: '日経225先物・mini・マイクロの片道と往復手数料、1ティックに対する比率を比較する。' },
  { slug: 'matsui-us-stock-trading-hours', category: '米国株・松井証券', title: '松井証券の米国株取引時間｜プレマーケットと23時間化予定', desc: '夏時間・冬時間のプレマーケットと通常取引時間、2026年12月予定の23時間化を時系列で整理する。' },
  { slug: 'matsui-us-stock-fx-fee', category: '米国株・松井証券', title: '松井証券の米国株は為替手数料0円？円貨決済25銭との違い', desc: '米ドルの事前両替0円と、円貨決済時の1ドル25銭を分け、取引金額ごとの負担を計算する。' },
  { slug: 'dmm-cfd-gold-vs-silver', category: 'CFD・DMM CFD', title: 'DMM CFDの金と銀｜1Lot・必要証拠金・金利調整額を比較', desc: '金1トロイオンス、銀10トロイオンスの取引単位と値動き・保有コストを比較する。' },
  { slug: 'dmm-cfd-commodity-lot-list', category: 'CFD・DMM CFD', title: 'DMM CFD商品14銘柄の1Lot一覧｜単位を間違えない早見表', desc: '金・銀・原油・天然ガス・農産物の1Lot単位と証拠金計算を一覧化する。' },
  { slug: 'dmm-cfd-natural-gas-vs-oil', category: 'CFD・DMM CFD', title: 'DMM CFDの天然ガスと原油｜1Lotの値動きと証拠金を比較', desc: '天然ガス100MMBtu、原油10バレルの取引単位と必要証拠金・価格調整額を比較する。' },
  { slug: 'dmm-cfd-agriculture-trading-hours', category: 'CFD・DMM CFD', title: 'DMM CFD農産物の取引時間｜コーン・大豆・小麦の休止時間', desc: '農産物CFDの分割された取引時間、夏冬時間、祝日・時間外注文の注意点を整理する。' },
  { slug: 'dmm-cfd-gold-vs-oil-cost', category: 'CFD・DMM CFD', title: 'DMM CFDの金と原油は何が違う？証拠金・調整額を比較', desc: '同じ商品CFDでも異なる取引単位、必要証拠金、金利調整額・価格調整額を整理する。' },
  { slug: 'nikkei225-futures-sq-settlement', category: '先物', title: '日経225先物のSQとは？取引最終日と最終決済を整理', desc: '第2金曜日、前営業日の取引終了、SQ値による差金決済を時系列で確認する。' },
  { slug: 'nikkei225-futures-night-session', category: '先物', title: '日経225先物の取引時間｜ナイトセッションは何日扱い？', desc: '日中8時45分〜15時45分、夜間17時〜翌6時と、取引日・祝日取引の考え方を整理する。' },
  { slug: 'matsui-nisa-fees', category: 'NISA・松井証券', title: '松井証券NISAは手数料無料？為替・信託報酬まで確認', desc: '日本株・米国株・投資信託の売買手数料0円と、別途残る為替手数料・信託報酬を分ける。' },
  { slug: 'matsui-one-day-margin-cost', category: '国内株・松井証券', title: '松井証券の一日信用は本当に無料？翌日持越しの費用', desc: 'ネット手数料、金利・貸株料、プレミアム空売り料、翌営業日の任意決済手数料を整理する。' },
  { slug: 'systre-select-365-strategy-selection', category: 'FX自動売買', title: 'シストレセレクト365のストラテジー選び｜利益率だけで決めない', desc: '最大ドローダウン、リスクリターン率、取引回数、推奨証拠金からストラテジーを比較する。' },
  { slug: 'systre-select-365-stop-switch', category: 'FX自動売買', title: 'シストレセレクト365の停止・入替え｜建玉を残さない確認手順', desc: '稼働停止、未決済ポジション、複数ストラテジーの両建て、サービス解約前の確認を整理する。' },
  { slug: 'matsui-fx-swap-calendar', category: 'FX・松井証券', title: 'MATSUI FXのスワップ付与時間｜1万通貨表示の計算方法', desc: '夏時間6時10分・冬時間7時10分以降の付与、付与日数、1通貨や100通貨へ換算する方法を整理する。' },
  { slug: 'matsui-fx-auto-trading-stop-restart', category: 'FX・松井証券', title: 'MATSUI FX自動売買の停止・再開｜建玉と注文はどうなる？', desc: '3つの運用停止方法、自動停止の条件、余力不足後に必要な再開操作を整理する。' },
  { slug: 'dmm-fx-swap-calendar', category: 'FX・DMM FX', title: 'DMM FXのスワップ付与日はいつ？0日・3日・4日の見方', desc: '営業日の切替時刻、通常の3日分、祝日による0日・4日分をスワップカレンダーから確認する。' },
  { slug: 'dmm-fx-slippage-orders', category: 'FX・DMM FX', title: 'DMM FXのスリッページ｜即時・指値・逆指値の違い', desc: '注文価格と約定価格がずれる条件、許容幅、注文不成立との関係を注文種類ごとに整理する。' },
  { slug: 'dmm-cfd-trading-hours', category: 'CFD・DMM CFD', title: 'DMM CFDの取引時間｜夏時間・冬時間と約定しない時間', desc: '日本225、米国指数、金・原油などの取引時間と、毎営業日のメンテナンス、祝日の注意点を整理する。' },
  { slug: 'dmm-cfd-adjustment-calendar', category: 'CFD・DMM CFD', title: 'DMM CFDの調整額カレンダー｜金利・価格調整の違い', desc: '金・銀の金利調整額と、指数・原油などの価格調整額を、発生日と注文への影響から整理する。' },
  { slug: 'systre-select-365-losscut-margin-shortage', category: 'FX自動売買', title: 'シストレセレクト365のロスカット｜有効比率100％と証拠金不足', desc: '1分ごとのロスカット、150％のアラート、取引終了後の証拠金不足を分ける。' },
  { slug: 'systre-select-365-vs-otc-fx', category: 'FX自動売買', title: 'シストレセレクト365と店頭FXの違い｜取引所FXを選ぶ意味', desc: '価格提示、スワップ、手数料、証拠金から、くりっく365と店頭FXの違いを整理する。' },
  { slug: 'matsui-fx-margin-call-losscut', category: 'FX・松井証券', title: 'MATSUI FXの追証とロスカット｜選べる50～90％を整理', desc: '取引終了時100％の追証判定と、個人口座で選べる50～90％のロスカット率を分ける。' },
  { slug: 'matsui-fx-spread-rules', category: 'FX・松井証券', title: 'MATSUI FXのスプレッドは0.1銭？時間・数量・注文条件', desc: '縮小スプレッドと通常スプレッドを、コアタイム、数量上限、注文種類から整理する。' },
  { slug: 'fxtf-minimum-unit-margin', category: 'FX・FXTF', title: 'FXTFは1,000通貨から？GX・MT4のLotと必要証拠金', desc: 'GXとMT4で異なるLot表記を通貨数へ直し、1,000通貨の必要証拠金と値動きによる損益を計算する。' },
  { slug: 'fxtf-gx-mt4-mt5-difference', category: 'FX・FXTF', title: 'FXTF GX・MT4・MT5の違い｜取引商品とツールを比較', desc: 'TradingView、EA、MT5の提供商品を整理し、取引目的に合うシステムを選ぶ。' },
  { slug: 'dmm-cfd-margin-call-losscut', category: 'CFD・DMM CFD', title: 'DMM CFDの追証とロスカットの違い｜100％・50％を整理', desc: '追加証拠金、マージンカット、リアルタイムのロスカットについて、判定時点と解消方法を分ける。' },
  { slug: 'cfd-vs-futures-nikkei225', category: 'CFD・先物', title: '日経225 CFDと先物の違い｜取引単位・期限・コストを比較', desc: '店頭取引と取引所取引、取引単位、限月、証拠金、スプレッド・手数料の違いを整理する。' },
  { slug: 'dmm-cfd-total-cost', category: 'CFD・DMM CFD', title: 'DMM CFDは手数料0円？スプレッド・調整額の総コスト', desc: '売買手数料0円と総コストを区別し、スプレッド、金利調整額、価格調整額、約定差を整理する。' },
  { slug: 'dmm-cfd-margin-leverage', category: 'CFD・DMM CFD', title: 'DMM CFDの必要証拠金はいくら？日本225・金・原油で計算', desc: '指数10倍・商品20倍の計算式と銘柄ごとの取引単位を使い、1Lotの必要額を試算する。' },
  { slug: 'systre-select-365-total-cost', category: 'FX自動売買', title: 'シストレセレクト365の手数料は0円？総コストを確認', desc: '初回990円の利用料、売買手数料、スプレッド、スワップを分け、自動売買の総負担を整理する。' },
  { slug: 'systre-select-365-recommended-margin', category: 'FX自動売買', title: 'シストレセレクト365の推奨証拠金とは？最大DDを計算', desc: '現在の証拠金基準額と過去1年の最大ドローダウンから、ストラテジー運用資金の目安を計算する。' },
  { slug: 'dmm-kabu-us-stock-fee', category: '米国株・DMM 株', title: 'DMM 株の米国株手数料はいくら？為替25銭まで計算', desc: '0ドルになる条件、0.495％・上限22ドルの取引手数料、円貨決済の為替コストを分けて試算する。' },
  { slug: 'dmm-kabu-domestic-round-trip-fee', category: '国内株・DMM 株', title: 'DMM 株の国内株手数料｜買って売る往復コストを計算', desc: '1注文ごとの料金表を使い、5万円から300万円超までの買付・売却合計を具体的に計算する。' },
  { slug: 'dmm-fx-margin-call-losscut', category: 'FX・DMM FX', title: 'DMM FXの追証とロスカットの違い｜100％と50％を整理', desc: '毎営業日の追加証拠金判定と、リアルタイムのロスカットを分け、証拠金維持率の読み方を整理する。' },
  { slug: 'dmm-fx-mini-normal-large', category: 'FX・DMM FX', title: 'DMM FXのミニ・通常・ラージの違い｜取引単位とコスト', desc: '1Lotの通貨数、必要証拠金、損益、原則固定スプレッドの対象を同じ条件で比較する。' },
  { slug: 'matsui-fx-auto-trading-cost', category: 'FX・自動売買', title: 'MATSUI FX自動売買は100円から？必要資金を計算', desc: '複数注文の必要証拠金と評価損を分け、100円で始める場合にも必要な余裕資金を整理する。' },
  { slug: 'matsui-fx-one-currency', category: 'FX・松井証券', title: 'MATSUI FXは100円から？1通貨の必要証拠金と損益', desc: '100円の意味を、為替レート・取引数量・レバレッジコースに分けて具体的に計算する。' },
  { slug: 'matsui-fx-one-currency-order', category: 'FX・松井証券', title: '松井証券FXの1通貨注文方法｜0.0001入力と数量表示の注意点', desc: '1万通貨単位で表示される数量欄の換算、PC・スマホの入力手順、証拠金・スプレッド・損益の確認を整理する。' },
  { slug: 'matsui-account-types', category: '証券・FX', title: '松井証券のFX専用口座と総合口座の違い', desc: 'FXだけを始める場合と、株・NISA・先物も利用する場合で異なる口座開設の入口を整理する。' },
  { slug: 'fx-zero-spread-total-cost', category: 'FX', title: 'FXの0.0銭は本当に無料？別手数料まで総額で確認', desc: 'ゼロスプレッドと取引コスト0円を区別し、数量連動手数料や約定差を含めて判断する。' },
  { slug: 'fx-swap-three-days', category: 'FX', title: 'FXのスワップが3日分・4日分付くのはなぜ？', desc: 'ロールオーバーと受渡日の関係、土日・祝日をまたぐ変則付与の確認方法を整理する。' },
  { slug: 'fx-margin-ratio-vs-usage', category: 'FX', title: '証拠金維持率と使用率の違い｜100%の意味は逆', desc: '維持率と使用率の計算方向を分け、ロスカットまでの余力を読み違えない方法。' },
  { slug: 'stock-round-trip-cost', category: '国内株', title: '株の往復コストはいくら？売買手数料と板の差を計算', desc: '買って売るまでの負担を、手数料・売値と買値の差・取引数量に分けて試算する。' },
  { slug: 'us-stock-fx-cost', category: '米国株', title: '米国株の為替コストを円で計算する方法', desc: '円貨決済と外貨決済の違いを整理し、1ドルあたりの為替コストを総額へ換算する。' },
  { slug: 'futures-tick-value', category: '先物', title: '先物の1ティックはいくら？日経225で計算', desc: 'ラージ・mini・マイクロの取引単位と呼値から、1ティックの損益額を計算する。' },
  { slug: 'futures-margin', category: '先物', title: '先物の証拠金と取引金額は何が違う？', desc: '証拠金を購入代金と混同しないために、取引金額・損益・VaR方式の関係を整理する。' },
  { slug: 'fx-spread-time', category: 'FX', title: 'FXのスプレッドが広がりやすい時間帯は？', desc: '広告表示の適用時間外や経済指標発表時に、取引コストが変わる理由と確認方法。' },
  { slug: 'fx-swap-calculation', category: 'FX', title: 'FXスワップポイントの計算方法', desc: '1Lotあたりの表示から、保有数量と付与日数に応じた金額を試算する。' },
  { slug: 'fx-required-margin', category: 'FX', title: 'FXの必要証拠金はいくら？1万通貨で計算', desc: '取引金額・必要証拠金・レバレッジの関係を、米ドル/円の例で整理する。' },
  { slug: 'cfd-price-adjustment', category: 'CFD', title: 'CFDの価格調整額とは？発生日と計算方法', desc: '先物を参照するCFDで発生する価格調整額の仕組みと、確認すべき日程・計算式。' },
  { slug: 'fx-spread-cost', category: 'FX', title: 'FXのスプレッドを円に直す方法', desc: '0.2銭という表示が、取引数量ごとに何円の負担になるかを計算する。' },
  { slug: 'hanbaijo-torihikijo', category: '暗号資産', title: '販売所と取引所は何が違うのか', desc: '同じ会社の中に2つの買い方がある理由と、コスト差が生まれる仕組み。' },
  { slug: 'spread-toha', category: '基礎知識', title: 'スプレッドとは何か — 「手数料無料」の正体', desc: '表示されない手数料がどこに含まれているかを、数字で追う。' },
  { slug: 'spread-hirogaru-toki', category: 'データの見方', title: 'スプレッドが広がるのはどんなときか', desc: '早朝・週末・相場急変時に何が起きているか。' },
  { slug: 'cost-no-uchiwake', category: '暗号資産', title: '暗号資産を買うときにかかるコストの全体像', desc: 'スプレッド以外に、入金・売買・送金・出金でいくらかかるのか。' },
  { slug: 'kounyu-tejun', category: '実務', title: 'コストを抑えて買うための手順', desc: '同じ金額を買うのに、どこで差がつくのかを順に確認する。' },
  { slug: 'tesuryo-hyoki', category: '基礎知識', title: '「手数料無料」はなぜ表示できるのか', desc: '表示として誤りではないが、負担がないという意味でもない。その構造。' },
  { slug: 'ita-yomikata', category: '実務', title: '取引所の「板」の読み方', desc: '指値と成行、そしてスプレッドが決まる仕組み。' },
  { slug: 'maker-taker', category: '基礎知識', title: 'メイカーとテイカー — 手数料が2種類ある理由', desc: '注文の出し方で手数料が変わる。その理由と実務上の意味。' },
  { slug: 'yogo', category: '用語', title: '金融コスト用語集', desc: '当サイトで使う用語を、計算との関係がわかるように整理します。' },
] as const;
