export const POSTS = [
  { slug: 'systre-select-365-total-cost', category: 'FX自動売買', title: 'シストレセレクト365の手数料は0円？総コストを確認', desc: '初回990円の利用料、売買手数料、スプレッド、スワップを分け、自動売買の総負担を整理する。' },
  { slug: 'systre-select-365-recommended-margin', category: 'FX自動売買', title: 'シストレセレクト365の推奨証拠金とは？最大DDを計算', desc: '現在の証拠金基準額と過去1年の最大ドローダウンから、ストラテジー運用資金の目安を計算する。' },
  { slug: 'dmm-kabu-us-stock-fee', category: '米国株・DMM 株', title: 'DMM 株の米国株手数料はいくら？為替25銭まで計算', desc: '0ドルになる条件、0.495％・上限22ドルの取引手数料、円貨決済の為替コストを分けて試算する。' },
  { slug: 'dmm-kabu-domestic-round-trip-fee', category: '国内株・DMM 株', title: 'DMM 株の国内株手数料｜買って売る往復コストを計算', desc: '1注文ごとの料金表を使い、5万円から300万円超までの買付・売却合計を具体的に計算する。' },
  { slug: 'dmm-fx-margin-call-losscut', category: 'FX・DMM FX', title: 'DMM FXの追証とロスカットの違い｜100％と50％を整理', desc: '毎営業日の追加証拠金判定と、リアルタイムのロスカットを分け、証拠金維持率の読み方を整理する。' },
  { slug: 'dmm-fx-mini-normal-large', category: 'FX・DMM FX', title: 'DMM FXのミニ・通常・ラージの違い｜取引単位とコスト', desc: '1Lotの通貨数、必要証拠金、損益、原則固定スプレッドの対象を同じ条件で比較する。' },
  { slug: 'matsui-fx-auto-trading-cost', category: 'FX・自動売買', title: 'MATSUI FX自動売買は100円から？必要資金を計算', desc: '複数注文の必要証拠金と評価損を分け、100円で始める場合にも必要な余裕資金を整理する。' },
  { slug: 'matsui-fx-one-currency', category: 'FX・松井証券', title: 'MATSUI FXは100円から？1通貨の必要証拠金と損益', desc: '100円の意味を、為替レート・取引数量・レバレッジコースに分けて具体的に計算する。' },
  { slug: 'matsui-account-types', category: '証券・FX', title: '松井証券のFX専用口座と総合口座の違い', desc: 'FXだけを始める場合と、株・NISA・先物も利用する場合で異なる口座開設の入口を整理する。' },
  { slug: 'fx-zero-spread-total-cost', category: 'FX', title: 'FXの0.0銭は本当に無料？別手数料まで総額で確認', desc: 'ゼロスプレッドと取引コスト0円を区別し、数量連動手数料や約定差を含めて判断する。' },
  { slug: 'fx-swap-three-days', category: 'FX', title: 'FXのスワップが3日分・4日分付くのはなぜ？', desc: 'ロールオーバーと受渡日の関係、土日・祝日をまたぐ変則付与の確認方法を整理する。' },
  { slug: 'fx-margin-ratio-vs-usage', category: 'FX', title: '証拠金維持率と使用率の違い｜100%の意味は逆', desc: '維持率と使用率の計算方向を分け、ロスカットまでの余力を読み違えない方法。' },
  { slug: 'stock-round-trip-cost', category: '国内株', title: '株の往復コストはいくら？売買手数料と板の差を計算', desc: '買って売るまでの負担を、手数料・売値と買値の差・取引数量に分けて試算する。' },
  { slug: 'us-stock-fx-cost', category: '米国株', title: '米国株の為替コストを円で計算する方法', desc: '円貨決済と外貨決済の違いを整理し、1ドルあたりの為替コストを総額へ換算する。' },
  { slug: 'futures-tick-value', category: '先物', title: '先物の1ティックはいくら？日経225で計算', desc: 'ラージ・mini・マイクロの取引単位と呼値から、1ティックの損益額を計算する。' },
  { slug: 'futures-margin', category: '先物', title: '先物の証拠金と取引金額は何が違う？', desc: '証拠金を購入代金と混同しないために、取引金額・損益・VaR方式の関係を整理する。' },
  { slug: 'fx-spread-time', category: 'FX', title: 'FXのスプレッドが広がりやすい時間帯は？', desc: '広告表示の適用時間外や経済指標発表時に、取引コストが変わる理由と確認方法。' },
  { slug: 'fx-swap-calculation', category: 'FX', title: 'FXスワップポイントの計算方法', desc: '1Lotあたりの表示から、保有数量と付与日数に応じた金額を試算する。' },
  { slug: 'fx-required-margin', category: 'FX', title: 'FXの必要証拠金はいくら？1万通貨で計算', desc: '取引金額・必要証拠金・レバレッジの関係を、米ドル/円の例で整理する。' },
  { slug: 'cfd-price-adjustment', category: 'CFD', title: 'CFDの価格調整額とは？発生日と計算方法', desc: '先物を参照するCFDで発生する価格調整額の仕組みと、確認すべき日程・計算式。' },
  { slug: 'fx-spread-cost', category: 'FX', title: 'FXのスプレッドを円に直す方法', desc: '0.2銭という表示が、取引数量ごとに何円の負担になるかを計算する。' },
  { slug: 'hanbaijo-torihikijo', category: '暗号資産', title: '販売所と取引所は何が違うのか', desc: '同じ会社の中に2つの買い方がある理由と、コスト差が生まれる仕組み。' },
  { slug: 'spread-toha', category: '基礎知識', title: 'スプレッドとは何か — 「手数料無料」の正体', desc: '表示されない手数料がどこに含まれているかを、数字で追う。' },
  { slug: 'spread-hirogaru-toki', category: 'データの見方', title: 'スプレッドが広がるのはどんなときか', desc: '早朝・週末・相場急変時に何が起きているか。' },
  { slug: 'cost-no-uchiwake', category: '暗号資産', title: '暗号資産を買うときにかかるコストの全体像', desc: 'スプレッド以外に、入金・売買・送金・出金でいくらかかるのか。' },
  { slug: 'kounyu-tejun', category: '実務', title: 'コストを抑えて買うための手順', desc: '同じ金額を買うのに、どこで差がつくのかを順に確認する。' },
  { slug: 'tesuryo-hyoki', category: '基礎知識', title: '「手数料無料」はなぜ表示できるのか', desc: '表示として誤りではないが、負担がないという意味でもない。その構造。' },
  { slug: 'ita-yomikata', category: '実務', title: '取引所の「板」の読み方', desc: '指値と成行、そしてスプレッドが決まる仕組み。' },
  { slug: 'maker-taker', category: '基礎知識', title: 'メイカーとテイカー — 手数料が2種類ある理由', desc: '注文の出し方で手数料が変わる。その理由と実務上の意味。' },
  { slug: 'yogo', category: '用語', title: '金融コスト用語集', desc: '当サイトで使う用語を、計算との関係がわかるように整理します。' },
] as const;
